print("Hello World! I'm a robot!")
print("Can you please give me a name?")
Name1 = input()
print("OOOOOOOooooOh, I love my new name " + Name1)
print("Can you please give me a favourite colour?")
colour = input()
print("OOOOOOOooooOh, I love my favourite colour " + colour)
print("Thanks for playing!")